language: c

sudo: false

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

install:
    ./build-all.sh

script:
    ./test-all.sh